const Cities = [
  {
    cityName: "GreenLand",
    imgUrl: 'greenland.png',
    visitors: 17,
    yourRank: 4,
    yourHighScore: 170,
    isLocked: false,
    price: 0,
  },
  {
    cityName: "Marinalia",
    imgUrl: 'marinalia.png',
    visitors: 12,
    yourRank: 3,
    yourHighScore: 120,
    isLocked: true,
    price: 500,
  },
  {
    cityName: "Royal City",
    imgUrl: 'royal-city.png',
    visitors: 12,
    yourRank: 3,
    yourHighScore: 120,
    isLocked: true,
    price: 750,
  },
  {
    cityName: "Factoria",
    imgUrl: 'factoria.png',
    visitors: 5,
    yourRank: '-',
    yourHighScore: '-',
    isLocked: true,
    price: 920,
  },
  {
    cityName: "Robopolis",
    imgUrl: 'robopolis.png',
    visitors: 5,
    yourRank: '-',
    yourHighScore: '-',
    isLocked: true,
    price: 1050,
  },
  {
    cityName: "Malltopia",
    imgUrl: 'malltopia.png',
    visitors: 3,
    yourRank: '-',
    yourHighScore: '-',
    isLocked: true,
    price: 1200,
  },
  {
    cityName: "Galaxia",
    imgUrl: 'galaxia.png',
    visitors: 1,
    yourRank: '-',
    yourHighScore: '-',
    isLocked: true,
    price: 1500,
  },
];

export default Cities;